### PR TITLE
vim.lsp.diagnostic has been moved to vim.diagnostic

### PR DESCRIPTION
**Pull request by abzcoding**
add support for neovim head diagnostics bcz of this commit
https://github.com/neovim/neovim/commit/2e8103475e18d1e4aa0d6355107f393815a886a6

### CODE REVIEW

**Comment by Pocco81** [comment]
Thanks for the contribution :)

**Comment by abzcoding** [comment]
thank you for this lovely theme

**Comment by Pocco81** [comment]
You're welcome :) any suggestions?

**Comment by abzcoding** [comment]
not much tbh its lovely as is, though i want variety so i'm using your theme in mornings 😅 
```lua
    {
      "Pocco81/Catppuccino.nvim",
      config = function()
        require("user/theme").catppuccino()
      end,
      cond = function()
        local _time = os.date "*t"
        return (_time.hour >= 7 and _time.hour < 11)
      end,
    }
```

**Pull request merged**
