### PR TITLE
feat: Catppuccin for xresources

### PR DESCRIPTION
**Pull request by Vapourium**
Sorry for the spam, just realized I could've reopened the last PR.

### CODE REVIEW

**Comment by Pocco81** [comment]
Oh don't worry about the spam, it's fine. So, talking about the PR, are you using the latest colors? I changed a bit the theme an hour ago. My question is, is the PR up-to-date with the [current palette](https://github.com/Pocco81/Catppuccino.nvim/blob/dev-remaster/lua/catppuccin/core/color_palette.lua)?

**Comment by Vapourium** [comment]
It is in fact. I based it off of the other extra configurations, namely alacritty.

**Comment by Pocco81** [comment]
Great! did you test it yet? do you have any screenshots? (if you don't mind sharing them, of course)

**Comment by Pocco81** [comment]
> It is in fact. I based it off of the other extra configurations, namely alacritty.

Yep, you got all of the colors right, I just checked :)

**Comment by Vapourium** [comment]
> Great! did you test it yet? do you have any screenshots? (if you don't mind sharing them, of course)

image

**Comment by Pocco81** [comment]
Really appreciated, thanks a lot!

**Comment by Vapourium** [comment]
I love it. To me, it's a bit like dracula but much easier on the eyes, and I can even use it at night. I kinda miss the other flavours, namely soft manilo.

**Comment by Pocco81** [comment]
Awwe thanks :)

> it's a bit like dracula

Dracula is one of my favorite themes too, my only complaint would be the super high contrast colors have; during the day it's perfect but it's just too bright to look at it in the dark lol. Also, fun fact: Dracula has 11 (12?) colors, Catppuccin has 16. 

> I kinda miss the other flavours, namely soft manilo.

There is a bit of every flavor in Catppuccin ;) Similar to my complaint with Dracula, Soft Manilo was perfect for the night due to it's low contrast and high paleness, but everything looked the same during the day lol.

I was actually thinking about adding Soft Manilos' brown to Catppuccin, but it didn't fit with the static.

**Pull request merged**
