### PR TITLE
Add Kitty themes

### PR DESCRIPTION
**Pull request by mrjones2014**
Adds a theme for Kitty terminal emulator, using the catppuccino theme colors.

### CODE REVIEW

**Comment by mrjones2014** [comment]
colors are all pulled from this file: https://github.com/Pocco81/Catppuccino.nvim/blob/main/lua/catppuccino/color_schemes/catppuccino.lua

**Comment by Pocco81** [comment]
Awesome! I was thinking it'd be great too to create Kitty themes for the other colorschemes, what do you think? (If this ever comes to be then we should organize this as `extras/neon_latte/kitty`, `extras/catppuccino/kitty`, ...)

**Comment by mrjones2014** [comment]
I added this one cause it's the one I personally use but I can add the others when I get time later today if you'd like.

**Comment by Pocco81** [comment]
Oh if you can it'd be great, truly appreciate it. I'll help too. Would you like to make Light Melya or Neon Latte?

**Comment by mrjones2014** [comment]
I can do Neon Latte. I'm more likely to use that one myself.

**Comment by Pocco81** [comment]
Great, I'll do Light Melya :)

**Comment by mrjones2014** [comment]
@Pocco81 I changed the directory organization and added the neon_latte theme 🚀

**Comment by Pocco81** [comment]
Light Melya is ready too: https://github.com/Pocco81/Catppuccino.nvim/pull/8/commits/43eef24bdb68a31c3519252436e857507db07c5b

**Comment by Pocco81** [comment]
Btw the Neon Latte one looks absolutely gorgeous. Great job!

**Comment by mrjones2014** [comment]
@Pocco81 most credit goes to you! I just copy/pasted the colors from your Lua file 😁

**Pull request merged**
